### ISSUE TITLE
Misleading license info

### ISSUE THREAD

**Issue by ufoq** [lieff/mp3-enc-bsd#1]
In project description it's written that it's licensed under BSD2, but I see that there are files from dist10 that are propertiary/LGPL (seen various versions).
It's unclear if author used BSD2 license only for code that was 'added' or got permission from original sources authors to change license.

**Comment by lieff** [comment]
Hmm, repo provided as-is form archive from some old linux distro.
I did not notice at first, but now I see there indeed files from dist10 reference code.
But are you sure dist10 is LGPL licensed? Only license mention there I see in dist10/doc/readme.dp.01.txt :
```
	These software programs are available to the user without any 
license fee or royalty on an "as is" basis.  ISO disclaims any and all 
warranties,  whether express, implied, or statuary, including any 
implied warranties or merchantability or of fitness for a particular 
purpose.  In no event shall ISO be liable for any incidental, punitive, 
or consequential damages of any kind whatsoever arising from the 
use of these programs.
```

**Comment by ufoq** [comment]
You are right, I didn't see that readme file with MPEG SSG License, so I thought it's proprietary. Also there are some projects that licensed dist10 sources as GPL (cos mpeg-ssg is gpl-compatible) what made my confusion even bigger. I think we can close this issue. Thank you for clarification.
